:Title: OGC Space Standards Domain Working Group Charter
:titletext: OGC Space Standards Domain Working Group Charter
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: 2023-08-29
|Approval Date:   2023-08-29
|Internal reference number of this OGC(R) document:    23-041r1
|Category: OGC(R) Domain Working Group Charter
|Authors:   Charles Heazel
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2023 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

== Introduction

This Domain Working Group (DWG) charter defines the role for OGC activities within the Space Domain and provides an open forum for the presentation and discussion of interoperability requirements, use cases, pilots, and implementations of OGC Standards in this domain. This Charter is to be presented to the OGC’s Technical and Planning Committees for consideration.

Domains are distinct Information Communities that defines a user domain where:

* A distinct market, application, or business approach exists;

* Common data definition, structure, syntax, and definitions exists;

* Common user requirements exist; and/or

* Common approach to vendors exists
This Charter defines the Space Domain as an information community which encompasses all spatiotemporal information and applications which are not centered on the planet Earth.   

=== Working Group

Operation of the OGC Space Domain Working Group follows the policies and procedures of the Technical Committee. The following definition from the Technical Policies and Procedures apply to this DWG Charter.

*Domain Working Group*: A group (organizationally, a subgroup of the TC) of individuals composed of members of the TC and invited guests, with the specific intent of solving some particular interoperability problem or problems in a particular technology domain for recommendation to the Technical Committee.

Functions of a Domain Working Group are as follows.

* Provide a forum for discussion and documentation of interoperability requirements for a given information or user community.

* Provide a forum to discuss and recommend document actions related to Interoperability Program Reports.

* Develop Change Requests Proposals (CRPs) for existing OGC Standards.

* Develop engineering reports with the intent of seeking approval by the TC for release of these documents as OGC White Papers, Discussion Papers or Best Practices Papers.

* Informational presentations and discussions about the market use of adopted OGC Standards.

* Have a formal approved charter that defines the DWGs Scope of Work and estimated timeline for completion of the work.

* Have all-member voting policies (unless otherwise stated).

* Have missions and goals defined by the TC.

A DWG [underline]#Does Not# work on Standards submissions, candidate Standards, or revisions to existing OGC Standards. However, a DWG can develop change requests as documentation of interoperability requirements that can then be submitted as work items to a Standards Working Group (SWG).

A DWG may determine that they wish to have public collaboration, such as in teleconference, email discussions, or a public twiki. In this case, the DWG shall make a motion to the TC to approve public participation in the DWG. Voting in DWGs is by simple majority of OGC Members present at the WG meeting, not just Voting TC Members, with the caveat that no OGC Member organization may cast more than one vote in a WG vote.

== Purpose of Working Group

This Charter defines the Space Domain as the area above the altitude where atmospheric effects on airborne objects become negligible. Specifically, the area surrounding the Earth at altitudes equal to, or greater than, 100 kilometers (54 nautical miles) above mean sea level. 

The Space Standards Domain Working Group will serve as a forum to identify requirements for standardization which are unique for the Space Domain, identify which organizations (if any) are addressing those requirements, and promote harmonization and integration of shared concepts across all Space standards.

== Problem statement

There is no common concept of “Space Standards”. The Space Domain is composed of a wide collection of initiatives, each addressing one part of the whole. Each of these initiatives develops their own standards and conventions. Attempts to harmonize across these initiatives are limited.

While the OGC cannot solve this problem for all disciplines, it can make sure that the concepts of space and time are consistent and interoperable across all communities in the Space Domain. In addition, the OGC can identify emerging Space Domain standards which would impact existing OGC Standards and encourage the impacted SWGs and DWGs to take appropriate action.

== Charter

The scope of the Space Standards DWG is to identify, develop, and promote interoperable spatiotemporal standards for application in non-terrestrial environments. 

The Space Standards DWG will coordinate with standards bodies and working groups both within and outside of the OGC in pursuit of this objective.

=== Charter members

The initial membership of the Space Standards Domain Working Group will consist of the following members and individuals with extensive education and experience in the Space Domain, namely:

|====
^|Name ^| Email ^| Organization
| Charles Heazel ^| mailto:cheazel@heazeltech.com[cheazel@heazeltech.com] ^| Heazeltech
| Carl Reed ^| mailto:carl.n.reed@gmail.com[carl.n.reed@gmail.com] ^| Carl Reed and Associates ^|
| Don Sullivan ^|| NASA

|====

=== Key activities

Key activities for the DWG include the following efforts:

. Serve as an coordinating body for all OGC Domain Working Groups working in the Space Domain.
. Decompose the Space Domain into a manageable set of sub-domains.
. Identify and document missions in the Space Domain which may have unique standardization requirements.
. Identify and document initiatives which are developing Space standards and conventions.
. Identify opportunities for the OGC to provide spatiotemporal data models, services, design patterns, and other architectural elements which can serve as a common capability across all Space standardization initiatives.
. Stay current on OGC Space related initiatives and be prepared to report on these efforts to other non-OGC initiatives.
. Liaison with Space standardization initiatives as needed to promote commonality in space-time concepts.
. Establish Standards Working Groups as needed to address Space related requirements which are not otherwise being addressed.

=== Business case

The domain for Space Standards is large and diverse. There is a risk that the standards, conventions, and practices arising from these diverse interests will be fragmented and non-interoperable. This Domain Working Group seeks to mitigate that risk by promoting space and time as a common enabling technology for all application communities in the Space Domain.

== Organizational approach and scope of work

=== Business goals

The Space Standards DWG will address the business case described above by working toward the following goals:

. Enable rational discussion of Space Standards by decomposing the Space Domain into more manageable sub-domains and/or mission areas.
. Identify existing Standards and common practices in the Space Domains.
. Establish liaison relations with key initiatives in Space Standards.
. Achieve consensus on concepts for space and time based on OGC Standards.
. Extend OGC Standards to support missions in the Space Domains.

=== Mission and Role

The Space Standards Domain Working Group will serve as a coordinating body for Space Standards, leading to interoperable representations for space and time across all Space Standards.

=== Activities planned for Space Standards DWG

The following activities are planned for the Space Standards DWG:

. Decompose the Space Domain into sub-domains, potentially including:
.. Lunar
.. Martian
.. Cislunar
.. Deep Space
. Develop a taxonomy of Space Missions including:
.. Mapping, Positioning, and Navigation
... Celestial and celestrial body-centirc coordinate reference systems
... Celestial mapping
... 3D+ positioning
... Navigation within and between coordinate reference systems
... Integration of general and special relativity
.. Space Situational Awareness
... Space Traffic Management
... Space debris tracking and removal
... Planetary/asset defense
... Orbit management
... Radio frequency spectrum management
.. Space Topology
... Space weather
... Space energy
.. Space Assets
... Digital twins / Space infrastructure
... Inhabitation plans
. Identify the information and computational capabilities needed to execute each mission.
. Identify capabilities shared across two or more missions
. Identify existing standards or standards development initiatives to address each capability
. Evaluate the body of standards for consistency, interoperability, and completeness
. Propose the formation of OGC Standards Working Groups as needed to address gaps in the body of Space standards.
. Engage with Space Standards development organizations in an attempt to better integrate Space Standards.
. Serve as the Standards Development Organization (SDO) for Space Standards that were not developed by a formal SDO. 

It is anticipated that a Reference Architecture will be required to support these tasks. Development of that Reference Architecture may be performed under this charter.

== Definitions

The following definitions apply to terms used in this Charter:

Space Domain: an information community which encompasses the area above the altitude where atmospheric effects on airborne objects become negligible https://www.jcs.mil/Portals/36/Documents/Doctrine/pubs/jp3_14ch1.pdf?ver=GfzdjuluCyyHDS9D_RtkNA%3D%3D[Space Operations, Joint Publication 3-14].

Cislunar: the large region of space in the Earth-Moon system beyond geosynchronous (GEO) orbit, including the Moon (https://www.whitehouse.gov/ostp/news-updates/2022/11/17/fact-sheet-first-national-cislunar-science-technology-strategy/[FACT SHEET: First National Cislunar Science & Technology Strategy])

== References

Some of the resources relevant to the work of this DWG are described below. Expanding this collection is one of the key objectives of this DWG.

* Consultative Committee for Space Data Systems (CCSDS): a multi-national forum for the development of communications & data systems standards for spaceflight. https://public.ccsds.org/Publications/AllPubs.aspx[https://public.ccsds.org/Publications/AllPubs.aspx]
* Flexible Image Transport System (FITS): a standard data format used in astronomy, https://fits.gsfc.nasa.gov/[https://fits.gsfc.nasa.gov/]
* Geospatial-Intelligence Standards Working Group (GWG) World Geodetic System and Geomatics Focus Group (WGSG): custodian of WGS84 and developer of the pending lunar "WGS84". https://gwg.nga.mil/gwg/focus-groups/World_Geodetic_System_&_Geomatics_(WGSG)_Focus_Gro.html[https://gwg.nga.mil/gwg/focus-groups/World_Geodetic_System_&_Geomatics_(WGSG)_Focus_Gro.html]
* ISO/TC 20/SC 13 - Space data and information transfer systems: an ISO body which works closely with the CCSDS. https://cwe.ccsds.org/cmc/docs/Forms/AllItems.aspx?RootFolder=/cmc/docs/ISO%20TC20-SC13%20Subcommittee&[https://cwe.ccsds.org/cmc/docs/Forms/AllItems.aspx?RootFolder=/cmc/docs/ISO%20TC20-SC13%20Subcommittee&]
* NASA DART Mission Web Site: an experiment to re-direct an astronomical body through kinetic impact. https://dart.jhuapl.edu/[https://dart.jhuapl.edu/]
* NASA Planetary Defense Coordination Office: https://www.nasa.gov/specials/pdco/index.html[https://www.nasa.gov/specials/pdco/index.html]
* NASA SPICE: a Toolkit for the development of space applications. https://naif.jpl.nasa.gov/naif/toolkit.html[https://naif.jpl.nasa.gov/naif/toolkit.html]
* Project Kuiper: Amazon's solution for LOE-based satellite internet. https://www.aboutamazon.com/what-we-do/devices-services/project-kuiper[https://ww.waboutamazon.com/what-we-do/devices-services/project-kuiper]
* USGS Planetary Analyis Ready Data (ARD): the USGS Astrogeology Science Center’s Analysis Ready Data portal. https://stac.astrogeology.usgs.gov/docs/[https://stac.astrogeology.usgs.gov/docs/]
* USGS Planetary Spatial Data Infrastructure (SDI): Spatial Data Infrastructures for the Moon, Europa, and other astronomical bodies. https://psdi.astrogeology.usgs.gov/[https://psdi.astrogeology.usgs.gov/]
